### ISSUE TITLE
Errores requesting access token

### ISSUE THREAD

**Issue by josemariaaguilera** [PCJones/Ultimate-Splinterlands-Bot-V2#106]
I'm getting this error when running the bot:

Error at requesting access token: System.NotImplementedException: The method or operation is not implemented.
   at HiveAPI.CS.CBase58.DecodePrivateWif(String data) in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Hive\CBase58.cs:line 25
   at Ultimate_Splinterlands_Bot_V2.Bot.BotInstance.RequestAccessTokenAsync() in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Bot\BotInstance.cs:line 444

**Comment by PCJones** [comment]
This means the posting key in your accounts.txt file is not correct. Please double check that you are using your private (not public) posting key and that there are no blank chars at the end

**Comment by NidroidX** [comment]
i have the same issue.
I'm trying to put my email and password bu is not working.
Thena i try with the username and the posting key but maybe i put the wrong one where i can find that.

**Comment by mamasexeno** [comment]
same issue.
