### ISSUE TITLE
Unable to get user cards.

### ISSUE THREAD

**Issue by Plloi** [PCJones/Ultimate-Splinterlands-Bot-V2#111]
Error: plloi: Could not get cards from splinterlands API: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ultimate_Splinterlands_Bot_V2.Model.UserCard..ctor(String cardId, String _card_long_id, String _level, Boolean _gold, Boolean _starter)
   at Ultimate_Splinterlands_Bot_V2.Api.SplinterlandsAPI.<>c.<GetPlayerCardsAsync>b__7_1(JToken x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at Ultimate_Splinterlands_Bot_V2.Api.SplinterlandsAPI.GetPlayerCardsAsync(String username, String accessToken)
Bot will play with phantom cards only.

**Comment by Plloi** [comment]
I bundled cardDetails.json in the release zip was missing cards, deleting it and forcing an update fixed it.
