### ISSUE TITLE
API 401 Unauthorised

### ISSUE THREAD

**Issue by ghost** [PCJones/Ultimate-Splinterlands-Bot-V2#116]
Hey! whenever I run the bot I get this error:

Error at WebRequest: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Ultimate_Splinterlands_Bot_V2.Http.HttpWebRequest.WebRequestPost(CookieContainer CookieContainer, String PostData, String Url, String UserAgent, String Referer, Encoding responseEncoding, String proxy)

I don't know what to do to fix this.

**Comment by ghost** [comment]
Just to add it only happens on modern not wild
