### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by mrksnlcln** [PCJones/Ultimate-Splinterlands-Bot-V2#23]
Error at team selection: OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@card_detail_id=151]"}
  (Session info: headless chrome=94.0.4606.81)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Ultimate_Splinterlands_Bot_V2.Classes.BotInstance.SelectTeam(IWebDriver driver, JToken team)

**Comment by PCJones** [comment]
Did the bot play a dragon team?

**Comment by PCJones** [comment]
It's a rare API bug that will get fixed soon. Sorry for the late reply
