### ISSUE TITLE
 Error at finding match

### ISSUE THREAD

**Issue by scorpius81** [PCJones/Ultimate-Splinterlands-Bot-V2#41]
I have install BOT on Ubuntu, when execute it  i see this error:

 Error: xxxx: Error at finding match: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ultimate_Splinterlands_Bot_V2.Classes.BotInstanceBlockchain.GetStringForSplinterlandsAPI(CtransactionData oTransaction) in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Classes\BotInstanceBlockchain.cs:line 52
   at Ultimate_Splinterlands_Bot_V2.Classes.BotInstanceBlockchain.StartNewMatch() in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Classes\BotInstanceBlockchain.cs:line 69
[14/11/2021 03:23:27] Warning: xxxxxx: Creating match was not successful: 
[14/11/2021 03:23:27] Warning: xxxxx: Sleeping for 5 minutes

**Comment by PCJones** [comment]
Hi, are you using username:posting_key in your accounts.txt?
Lightning mode does not work with password or master key

**Comment by PCJones** [comment]
Feel free to reopen this if you still have this problem
