### ISSUE TITLE
Match not starting / team selection error

### ISSUE THREAD

**Issue by lilszi** [PCJones/Ultimate-Splinterlands-Bot-V2#58]
Error at team selection: OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@card_detail_id=361]"}
  (Session info: headless chrome=95.0.4638.69)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Ultimate_Splinterlands_Bot_V2.Classes.BotInstanceBrowser.SelectTeam(IWebDriver driver, JToken team) in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Classes\BotInstanceBrowser.cs:line 435

**Comment by np005045523** [comment]
same.. what to do?

**Comment by PCJones** [comment]
Don't use browser mode, use lightning mode. Browser mode is no longer supported
