### ISSUE TITLE
Unable to find Access Tokens in Lightning Mode

### ISSUE THREAD

**Issue by Aciescognito** [PCJones/Ultimate-Splinterlands-Bot-V2#67]
Hello, I tried setting up your bot, it won't run on lightning mode, but works just fine on browser mode.

Email@gmail.com: Requesting access token... (this only happens once per account)
[3/4/2022 10:22:32 PM] Error: Email@gmail.com: Error at requesting access token: System.NotImplementedException: The method or operation is not implemented.
   at HiveAPI.CS.CBase58.DecodePrivateWif(String data)
   at Ultimate_Splinterlands_Bot_V2.Classes.BotInstanceBlockchain.GetAccessTokenAsync()

**Comment by PCJones** [comment]
E-Mail Login is no longer supported, please use username and posting key

**Comment by Aciescognito** [comment]
Ok, thanks.
