### ISSUE TITLE
Critical Error API Error

### ISSUE THREAD

**Issue by meloer** [PCJones/Ultimate-Splinterlands-Bot-V2#7]
I got this Critical Error API Error.

> Critical Error: kaldeyn: API Error: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Ultimate_Splinterlands_Bot_V2.Classes.API.PostJSONToApi(Object json, String url, String username)
   at Ultimate_Splinterlands_Bot_V2.Classes.API.GetTeamFromAPIAsync(Int32 mana, String rules, String[] splinters, String[] cards, JToken quest, String username)
[9/28/2021 1:00:37 PM] Critical Error: kaldeyn: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ultimate_Splinterlands_Bot_V2.Classes.BotInstance.DoBattleAsync(IWebDriver driver, Boolean logoutNeeded)
Skipping Account

**Comment by PCJones** [comment]
Trying to reproduce this bug but it's working for me so far

**Comment by PCJones** [comment]
Happens when the API is overloaded, the newest version is trying to ask the API a second time if the error occurs.

**Comment by PCJones** [comment]
Fixed for a long time
