### ISSUE TITLE
Error at requesting access token: System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by sparkjames** [PCJones/Ultimate-Splinterlands-Bot-V2#91]
Running OS X 12.4 on a Macbook Pro. Trying to run the bot which I usually run on  Pop OS with no issue, but here it can't get an access token.

Here is a copy of the terminal ourput:

```
[8/7/2022 5:11:11 PM] --------------------------------------------------------------
[8/7/2022 5:11:11 PM] Ultimate Splinterlands Bot V2 by PC Jones
[8/7/2022 5:11:11 PM] Join the telegram group https://t.me/ultimatesplinterlandsbot
[8/7/2022 5:11:11 PM] Join the discord server https://discord.gg/hwSr7KNGs9
[8/7/2022 5:11:11 PM]                Close this window to stop the bot
[8/7/2022 5:11:11 PM]    Or write stop and press enter to stop the bot
[8/7/2022 5:11:11 PM] -------------------------------------------------------------
[8/7/2022 5:11:11 PM] Reading config...
[8/7/2022 5:11:11 PM] Config loaded!
[8/7/2022 5:11:11 PM] Config parameters:
MODE: LIGHTNING (blockchain)
DEBUG: False
AUTO_UPDATE: True
WRITE_LOG_TO_FILE: False
SHOW_API_RESPONSE: True
PRIORITIZE_QUEST: True
CLAIM_QUEST_REWARD: True
CLAIM_SEASON_REWARD: True
REQUEST_NEW_QUEST: snipe
ADVANCE_LEAGUE: True
SLEEP_BETWEEN_BATTLES: 5
START_BATTLE_ABOVE_ECR: 0
STOP_BATTLE_BELOW_ECR: 30
USE_API: True
USE_PRIVATE_API: False
POWER_TRANSFER_BOT: False 
SHOW_BATTLE_RESULTS: True 
THREADS: 1 
CardSettings { USE_CARD_SETTINGS = False, WINRATE_MODIFIER_OWNED_CARD_PERCENTAGE = 24, FLAT_NEGATIVE_MODIFIER_PER_UNOWNED_CARD = 2.5, USE_FOCUS_ELEMENT_WINRATE_THRESHOLD = 55, PREFERRED_SUMMONER_ELEMENTS_WINRATE_THRESHOLD = 48, PREFERRED_SUMMONER_ELEMENTS = System.String[], CARD_MIN_LEVEL = 1, ADD_ZERO_MANA_CARDS = True, PLAY_STARTER_CARDS = True, DISABLE_OWNED_CARDS_PREFERENCE_BEFORE_CHEST_LEAGUE_RATING = True, DISABLE_FOCUS_PRIORITY_BEFORE_CHEST_LEAGUE_RATING = True, WINRAT }THRESHOLD = 40, MINIMUM_GAMES = 10, PREFERRED_SUMMONER_ELEMENT = 
[8/7/2022 5:11:11 PM] Reading accounts.txt...
[8/7/2022 5:11:11 PM] sparkjames: Requesting access token... (this only happens once per account)
[8/7/2022 5:11:11 PM] Error: sparkjames: Error at requesting access token: System.NotImplementedException: The method or operation is not implemented.
   at HiveAPI.CS.CBase58.DecodePrivateWif(String data) in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Hive\CBase58.cs:line 25
   at Ultimate_Splinterlands_Bot_V2.Bot.BotInstance.GetAccessTokenAsync() in D:\Coding\C#\Projects\Splinterlands Battle API\Ultimate Splinterlands Bot V2\Bot\BotInstance.cs:line 390
```

If any other info would be helpful let me know.

**Comment by PCJones** [comment]
Sorry for the late response.
Make sure to use the correct private posting key, then it should work just fine

**Comment by PCJones** [comment]
Feel free to create a new issue if this problem persists
